# 共通設定（default）
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# 自分のPCで動かす時の設定（development）
development:
  <<: *default
  database: storage/development.sqlite3

# テストを自動実行する時の設定（test）
test:
  <<: *default
  database: storage/test.sqlite3

# --- ここからが本番（Render）用の設定 ---
production:
  # ここでアダプターを postgresql に切り替える
  adapter: postgresql
  encoding: unicode
  # Renderの環境変数 DATABASE_URL から接続情報を読み込む
  url: <%= ENV.fetch("DATABASE_URL") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>